
CREATE SEQUENCE CONTROL_DWP.LOADING_LOAD_ID_SEQ
  START WITH 100
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE SEQUENCE CONTROL_DWP.LOADING_EVENT_EVENT_ID_SEQ
  START WITH 100
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;  

--------------------------------------------------------------------------------
CREATE TABLE CONTROL_DWP.ARCHIVE_ATTRIBUTE
(
  ARCHIVE_ID       NUMBER                       NOT NULL,
  ATTRIBUTE_CODE   VARCHAR2(3 BYTE)             NOT NULL,
  ATTRIBUTE_VALUE  VARCHAR2(256 BYTE)
);


COMMENT ON TABLE CONTROL_DWP.ARCHIVE_ATTRIBUTE IS 'Attributes of .zip-file';

COMMENT ON COLUMN CONTROL_DWP.ARCHIVE_ATTRIBUTE.ARCHIVE_ID IS 'Identifier of .zip-file';

COMMENT ON COLUMN CONTROL_DWP.ARCHIVE_ATTRIBUTE.ATTRIBUTE_CODE IS 'Char-code of the attribute, e.g.: NAM - name, TYP - type. Full list is in Paremetr Set CONSTANTS_PS';

COMMENT ON COLUMN CONTROL_DWP.ARCHIVE_ATTRIBUTE.ATTRIBUTE_VALUE IS 'Value of the attribute';


CREATE UNIQUE INDEX CONTROL_DWP.ARCHIVE_ATTRIBUTE_PK ON CONTROL_DWP.ARCHIVE_ATTRIBUTE
(ARCHIVE_ID, ATTRIBUTE_CODE);


ALTER TABLE CONTROL_DWP.ARCHIVE_ATTRIBUTE ADD (
  CONSTRAINT ARCHIVE_ATTRIBUTE_PK
  PRIMARY KEY
  (ARCHIVE_ID, ATTRIBUTE_CODE)
  USING INDEX CONTROL_DWP.ARCHIVE_ATTRIBUTE_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON CONTROL_DWP.ARCHIVE_ATTRIBUTE TO DWHADM;
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
CREATE TABLE CONTROL_DWP.LOADING
(
  LOAD_ID     NUMBER                            NOT NULL,
  ARCHIVE_ID  NUMBER                            NOT NULL,
  PPN_DT      DATE                              NOT NULL
);

COMMENT ON TABLE CONTROL_DWP.LOADING IS 'Register of .zip-file receivings';

COMMENT ON COLUMN CONTROL_DWP.LOADING.LOAD_ID IS 'Identifier of receiving';

COMMENT ON COLUMN CONTROL_DWP.LOADING.ARCHIVE_ID IS 'Identifier of .zip-file';

COMMENT ON COLUMN CONTROL_DWP.LOADING.PPN_DT IS 'Date-time point of receiving';

CREATE UNIQUE INDEX CONTROL_DWP.LOADING_PK ON CONTROL_DWP.LOADING(LOAD_ID);

CREATE OR REPLACE TRIGGER CONTROL_DWP.LOADING_LOAD_ID_TRG
BEFORE INSERT
ON CONTROL_DWP.LOADING
FOR EACH ROW
WHEN (
new.load_id is null
      )
BEGIN
  select control_dwp.loading_load_id_seq.nextval into :new.load_id from dual;
END;
/

ALTER TABLE CONTROL_DWP.LOADING ADD (
  CONSTRAINT LOADING_PK
  PRIMARY KEY
  (LOAD_ID)
  USING INDEX CONTROL_DWP.LOADING_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON CONTROL_DWP.LOADING TO DWHADM;
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
CREATE TABLE CONTROL_DWP.LOADING_EVENT
(
  EVENT_ID    NUMBER                            NOT NULL,
  LOAD_ID     NUMBER                            NOT NULL,
  EVENT_CODE  VARCHAR2(5 BYTE)                  NOT NULL,
  PPN_DT      DATE                              NOT NULL
);

COMMENT ON TABLE CONTROL_DWP.LOADING_EVENT IS 'Journal of loading events';

COMMENT ON COLUMN CONTROL_DWP.LOADING_EVENT.EVENT_ID IS 'Identifier of event';

COMMENT ON COLUMN CONTROL_DWP.LOADING_EVENT.LOAD_ID IS 'Identifier of receiving';

COMMENT ON COLUMN CONTROL_DWP.LOADING_EVENT.EVENT_CODE IS 'Char-code of event';

COMMENT ON COLUMN CONTROL_DWP.LOADING_EVENT.PPN_DT IS 'Date-time point of event';

CREATE UNIQUE INDEX CONTROL_DWP.LOADING_EVENT_PK ON CONTROL_DWP.LOADING_EVENT
(EVENT_ID);

CREATE OR REPLACE TRIGGER CONTROL_DWP.LOADING_EVENT_EVENT_ID_TRG
BEFORE INSERT
ON CONTROL_DWP.LOADING_EVENT
FOR EACH ROW
WHEN (
new.event_id is null
      )
BEGIN
  select control_dwp.loading_event_event_id_seq.nextval into :new.event_id from dual;
END;
/

ALTER TABLE CONTROL_DWP.LOADING_EVENT ADD (
  CONSTRAINT LOADING_EVENT_PK
  PRIMARY KEY
  (EVENT_ID)
  USING INDEX CONTROL_DWP.LOADING_EVENT_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON CONTROL_DWP.LOADING_EVENT TO DWHADM;
-------------------------------------------------------------------------------